spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/messenger?ApplicationName=messenger
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /views/
      suffix: .jsp